EWB-2445: Add examples 1 through 6
zepben/ewb-sdk-examples-python pull request #1
Opened 2022-11-15 00:52 UTC by Lax125

Signed-off-by: Marcus Koh <marcus.koh@zepben.com>

# Description

Adds examples 1 through 6, as described in https://app.clickup.com/t/6929263/EWB-2444

# Associated tasks:

- No tasks blocking this one, nor blocked by this one.

# Checklist:

- [ ] I have performed a self review of my own code.
- [ ] I have updated the changelog.
- [ ] I have handled all new warnings generated by the compiler or IDE.

2022-11-17 04:56 UTC, Lax125 commented
@kgreav This is just a rough first draft, give it s skim and let me know of any high-level suggestions so I can revise it further. I combined fetching the model and inspecting it into the same example.

2022-11-17 05:24 UTC, Lax125 commented on src/zepben/examples/fetching_network_model.py
> +    channel = connect_with_password(host="dev.ewb.essential.zepben.com",
@sonatype-lift ignore

2022-11-18 00:17 UTC, kgreav requested changes
Looking really good - maybe just add a really contrived network example (like source -> line -> fuse -> transformer -> fuse -> breaker -> line -> consumer) with an ASCII diagram.
In that example can you also document and use NetworkService.add_connectivity_node() 

Once you have the above maybe use it to give some examples exploring connectivity? of that model?

2022-11-18 00:17 UTC, kgreav commented on src/zepben/examples/network_hierarchy.py
> +)
Be nice if we could print a tree hierarchy here of this, starting from the GeographicalRegion - maybe give them human readable names too? E.g:

```
for sgr in gr_nsw.sub_geographical_regions:
    print(f"- {sgr.name}) # add some nice formatting - doesn't have to exactly be a tree, just make the structure clear
    for sub in sgr.substations:
        print(...)
```

2022-11-18 00:17 UTC, kgreav commented on src/zepben/examples/network_service_interactions.py
> +name_type.get_or_add_name("53220", breaker)
use correct NMIs for this - 9 numbers at least

2022-11-18 00:17 UTC, kgreav commented on src/zepben/examples/fetching_network_model.py
> +    client.get_equipment_container(feeder_mrid, include_energized_containers=INCLUDE_ENERGIZED_LV_FEEDERS).throw_on_error()
can we have a few similar examples for the other include_energized_containers and include_energizing_containers functions with descriptions?

2022-11-18 00:17 UTC, kgreav commented on src/zepben/examples/connecting_to_grpc_service.py
> +# You may use `SyncNetworkConsumerClient` if you prefer not to use asyncio
Maybe just add a comment here that the API on SyncNetworkConsumerClient is the same

2022-11-22 05:15 UTC, Lax125 commented on src/zepben/examples/fetching_network_model.py
> +    channel = connect_with_password(host="EWB hostname",
@sonatype-lift ignore

2022-11-22 05:16 UTC, Lax125 commented on src/zepben/examples/network_hierarchy.py
> +nh = NetworkHierarchy(
@sonatype-lift ignore

2022-11-22 05:16 UTC, Lax125 commented on src/zepben/examples/ieee_13_node_test_feeder.py
> +    r_per_foot, x_per_foot = numpy.mean(impedances, axis=0) / FEET_PER_MILE
@sonatype-lift ignore

2022-11-22 05:16 UTC, Lax125 commented on src/zepben/examples/network_hierarchy.py
> +network_hierarchy = NetworkHierarchy(
@sonatype-lift ignore

2022-11-22 05:17 UTC, Lax125 commented on src/zepben/examples/network_service_interactions.py
> +name_type = NameType(name="NMI", description="National Meter Identifier")
@sonatype-lift ignore

2022-11-22 23:49 UTC, Lax125 commented
Tests not needed for example usage code.

2022-12-02 05:02 UTC, kgreav approved these changes

2022-12-02 05:06 UTC, merged