[DEV-1752] hcm intervention data model change
zepben/ewb-sdk-examples-python pull request #16
Opened 2024-12-03 03:34 UTC by Esaotuelr

# Description

Update setup file to include new python sdk and remove unused install packages.
None of the changes should impact any of the examples.

# Associated tasks

[grpc](https://github.com/zepben/ewb-grpc/pull/120)
[python sdk](https://github.com/zepben/ewb-sdk-python/pull/162)

# Test Steps

I just ran tracing.py to see if it broke anything.

# Checklist

If any of these are not applicable, strikethrough the line `~like this~`. **Do not delete it!**. Let the reviewer decide if you should have done it.

### Code
~- [ ] I have performed a self review of my own code (including checking issues raised when creating the PR).~
~- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.~
~- [ ] I have commented my code in any hard-to-understand or hacky areas.~
- [x] I have handled all new warnings generated by the compiler or IDE.
- [x] I have rebased onto the target branch (usually main).

### Documentation
- [x] I have updated the changelog.
~- [ ] I have updated any documentation required for these changes.~

# Breaking Changes
- [x] I have considered if this is a breaking change and will communicate it with other team members if so.

There is a bit of a jump from previous version. The change introduced in the newest sdk update shouldn't break anything and looking at release tag / update history there shouldn't be breaking changes that affects the example repo.

2025-01-10 00:00 UTC, charlta requested changes

2025-01-10 00:00 UTC, charlta commented on changelog.md
> +* support zepben.evolve up to 0.43.0.
nit: Capitalise and code block
```suggestion
* Support `zepben.eas` up to 0.15.0.
* Support `zepben.evolve` up to 0.43.0.
```

2025-01-15 06:00 UTC, Esaotuelr commented on changelog.md
> +* restrict installation to supported Python versions from 3.9 to 3.12
Changed it up, and also need to limit to 3.11 apparently.

2025-01-15 06:01 UTC, Esaotuelr commented on changelog.md
> +* support zepben.evolve up to 0.43.0.
Changed and changed eas version to 0.16.0 too

2025-01-16 04:32 UTC, charlta approved these changes

2025-01-17 01:36 UTC, merged