Ewb 2446 example traces
zepben/ewb-sdk-examples-python pull request #2
Opened 2022-11-24 04:01 UTC by Lax125

# Description

Add examples of using tracing, specifically the traversal functions in the `tracing` module.

# Associated tasks:

Tasks blocking this one:
- EWB-2527 (PR TBA)

Tasks this is blocking:
- None

# Checklist:

- [ ] I have performed a self review of my own code.
- [ ] I have added/updated unit tests for these changes, and if not I have explained why they are not necessary.
- [ ] I have updated the changelog.
- [ ] I have handled all new warnings generated by the compiler or IDE.

2022-12-02 05:12 UTC, kgreav commented
Sorry merged your other PR and will probably cause you some rebase pain here...
You'll want to use `git rebase -i --onto main <branch>` or something similar to make sure you only get the commits from this branch.

2023-01-09 04:43 UTC, Lax125 commented on src/zepben/examples/fetching_network_model.py
> +    channel = connect_with_password(host="EWB hostname",
No actual password here.

2023-01-09 04:43 UTC, Lax125 commented on src/zepben/examples/fetching_network_model.py
> +    channel = connect_with_password(host="EWB hostname",
@sonatype-lift ignore

2023-01-09 04:44 UTC, Lax125 commented
No tests needed for example code.

2023-01-09 05:27 UTC, kgreav requested changes
very good sir - only minor comments/questions.

we can probably merge it after you make the fixes and then get krishneel to test/document them based off this in the docusaurus repo, and any fixes/improvements he makes we can incorporate here.

2023-01-09 05:27 UTC, kgreav commented on src/zepben/examples/tracing.py
> +    # The normal connected equipment trace iterates through all equipment normally connected to the starting equipment.
reword this to "all equipment connected to the starting equipment in the networks' normal state"

2023-01-09 05:27 UTC, kgreav commented on src/zepben/examples/tracing.py
> +    network.get("sw_671_692", Switch).set_normally_open(True, phase=SinglePhaseKind.A)
so even if other phases are closed on the switch this trace doesn't trace through them? if that's the case can you mention that explicitly?
seems like a weird behaviour though...

2023-01-09 05:27 UTC, kgreav commented on src/zepben/examples/tracing.py
> +    switch.set_normally_open(True, phase=SinglePhaseKind.B)
looks like you've typo'd normal/normally here and it should be current/currently.

Probably worth rewording the comment like i've suggested above as well.

2023-01-09 05:27 UTC, kgreav commented on src/zepben/examples/tracing.py
> +    # and likewise does not go through switches with at least open phase.
typo: at least one open phase

2023-01-09 05:55 UTC, Lax125 commented on src/zepben/examples/tracing.py
> +    # and likewise does not go through switches with at least open phase.
Fixed

2023-01-09 05:56 UTC, Lax125 commented on src/zepben/examples/tracing.py
> +    network.get("sw_671_692", Switch).set_normally_open(True, phase=SinglePhaseKind.A)
It's how tracing works on the JVM sdk version too AFAIK, so this doesn't seem like a bug. I think phase traces are used instead in cases where you do want it to go through.

2023-01-09 05:57 UTC, Lax125 commented on src/zepben/examples/tracing.py
> +    switch.set_normally_open(True, phase=SinglePhaseKind.B)
Fixed typo and reworded.

2023-01-09 05:57 UTC, Lax125 commented on src/zepben/examples/tracing.py
> +    # The normal connected equipment trace iterates through all equipment normally connected to the starting equipment.
Done.

2023-01-09 11:56 UTC, kgreav approved these changes

2023-01-09 11:56 UTC, merged